//
// Created by Christian nahuel Rivera on 16/6/19.
//

#ifndef AED3_TP3_DEFINES_H
#define AED3_TP3_DEFINES_H


#define FICHA_ENEMIGA 0
#define FICHA_ALIADA 1
#define VACIO 2
#define FICHA_TEST 3

#define STRATEGY_NAME int
#define PESO int
#define FICHA int

#define HORIZONTAL_OFENSIVO 1
#define HORIZONTAL_DEFENSIVO 2
#define VERTICAL_OFENSIVO 3
#define VERTICAL_DEFENSIVO 4
#define DIAGONAL_45_OFENSIVO 5
#define DIAGONAL_45_DEFENSIVO 6
#define DIAGONAL_315_OFENSIVO 7
#define DIAGONAL_315_DEFENSIVO 8
#define JUGADA_ALEATORIA 9



#endif //AED3_TP3_DEFINES_H
